apiVersion: v1
kind: Secret
metadata:
  name: cricket-secrets
  namespace: {{ include "cricket-app.namespace" . }}
  labels:
    {{- include "cricket-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.env.databaseUrl | quote }}
  REDIS_URL: {{ .Values.backend.env.redisUrl | quote }}
  ADMIN_PASSWORD: {{ .Values.backend.env.adminPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.env.postgresPassword | quote }}
