apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "cricket-app.namespace" . }}
  labels:
    app: backend
    {{- include "cricket-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
