cidr_block  = "10.0.0.0/16"
azs         = ["ap-south-1a", "ap-south-1b"]
global_cidr = "0.0.0.0/0"
container_port = 80
backend_port = 3001
db_port = 5432
cache_port = 6379
https_port = 443
zero_port = 0
services = ["frontend", "backend", "db", "cache"]
namespace = "local"
ttl = 60
CLUSTER_NAME = "memecricket-fargate-cluster"
log_driver = "awslogs"
region = "ap-south-1"
cpu = "256"
memory = "512"
network_mode = "awsvpc"
retention_days = 7
db_cpu = "512"
db_memory = "1024"
POSTGRES_DB = "cricket_db"
POSTGRES_USER = "cricket"
desired_count = 0