apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ include "cricket-app.namespace" . }}
  labels:
    app: frontend
    {{- include "cricket-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
