apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ include "cricket-app.namespace" . }}
  labels:
    app: database
    {{- include "cricket-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  selector:
    app: database
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.containerPort }}
      protocol: TCP
      name: postgres
  clusterIP: None  # Headless service for StatefulSet
