
// ========== Functions ==========
def setup() {
    env.AWS_ACCOUNT_ID = sh(script: "aws sts get-caller-identity --query Account --output text", returnStdout: true).trim()
    env.ECR_REPOSITORY = "dev-frontend-memecricket"
}

def buildAndPush() {
    sh 'aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY'
    sh 'docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .'
    sh 'docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG'
}

def pullTagAndPush(envName){
    sh 'docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG'
    sh 'docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/${envName}-frontend-memecricket:$IMAGE_TAG'
    sh 'docker push $ECR_REGISTRY/${envName}-frontend-memecricket:$IMAGE_TAG'
}

def trivyScan(envName) {
    sh 'trivy image --exit-code 0 --severity HIGH,CRITICAL $ECR_REGISTRY/${envName}-frontend-memecricket:$IMAGE_TAG'
}

def deployToECS(envName) {
    // def ENV_CONFIG = [
    //     dev:     [ CLUSTER_NAME: 'memecricket-dev-cluster' ],
    //     staging: [ CLUSTER_NAME: 'memecricket-staging-cluster' ],
    //     prod:    [ CLUSTER_NAME: 'memecricket-prod-cluster' ]
    // ]
    env.CLUSTER_NAME = 'memecricket-${envName}-cluster'
    sh '''
        export EXECUTION_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/ecs-task-execution-role"
        export IMAGE_URI="${ECR_REGISTRY}/${envName}-frontend-memecricket:${IMAGE_TAG}"
        export BACKEND_URL="backend.${envName}.cricket.local:3001"

        envsubst < container-app/ecs/frontend-task-def.json > frontend-task-def-ready.json

        aws ecs register-task-definition --cli-input-json file://frontend-task-def-ready.json --region ${AWS_DEFAULT_REGION}
        aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --task-definition ${TASK_FAMILY} --force-new-deployment --region ${AWS_DEFAULT_REGION}
    '''
}

def cleanup() {
    sh 'docker logout $ECR_REGISTRY || true'
    sh 'docker system prune -f --filter "label!=keep" || true'
    cleanWs()
}

// ========== Pipeline ==========
pipeline {
    agent any
    // parameters {
    //     choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Target deployment environment')
    // }
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        ECR_REGISTRY          = credentials('ECR_REGISTRY')
        AWS_DEFAULT_REGION    = 'ap-south-1'
        SERVICE_NAME          = 'frontend-service'
        TASK_FAMILY           = 'frontend-task'
        IMAGE_TAG             = "v${BUILD_NUMBER}"
    }
    stages {
        stage('Setup') {
            steps {
                script { setup() }
            }
        }
        stage('Build & Push to DEV') {
            steps {
                dir('src/frontend') {
                    script { buildAndPush() }
                }
            }
        }
        stage('Security Scan DEV') {
            steps {
                script { trivyScan("dev") }
            }
        }
        stage('Deploy to ECS DEV') {
            steps {
                script { deployToECS("dev") }
            }
        }
        stage('pull and push image to QA'){
            steps {
                script { pullTagAndPush("qa") }
            }
        }
        stage('DEploy to ECS in QA'){
            steps {
                script { deployToECS("qa") }
            }
        }
        stage('Approve Prod Deployment') {
            steps {
                input message: "Deploy ${IMAGE_TAG} to PRODUCTION?", ok: 'Deploy'
            }
        }
        stage('pull and push image to PROD'){
            steps {
                script { pullTagAndPush("prod") }
            }
        }
        stage('DEploy to ECS in QA'){
            steps {
                script { deployToECS("prod") }
            }
        }
    }
    post {
        always {
            script { cleanup() }
            echo 'Pipeline execution complete. Workspace cleaned.'
        }
        success { echo "✅ ${params.ENVIRONMENT} Deployment successful! Image: ${IMAGE_TAG}" }
        failure { echo "❌ ${params.ENVIRONMENT} Pipeline failed. Please check the logs." }
    }
}
